name: Native Image
on:
  push:
    branches:
      - master
      - main
  pull_request:
  release:
    types: [published]
jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        include:
          # Replace "example" with the name your binary
          - os: macOS-latest
            uploaded_filename_1: example-x86_64-apple-darwin
            local_path_1: example/target/native-image/example
            uploaded_filename_2: example-x86_64-apple-darwin
            local_path_2: example/target/native-image/example
          - os: ubuntu-latest
            uploaded_filename_1: example-x86_64-pc-linux
            local_path_1: example/target/native-image/example
            uploaded_filename_2: example-x86_64-pc-linux
            local_path_2: example/target/native-image/example
          - os: windows-latest
            uploaded_filename_1: example-x86_64-pc-win32.exe
            local_path_1: example\target\native-image\example.exe
            uploaded_filename_2: example-x86_64-pc-win32.exe
            local_path_2: example\target\native-image\example.exe
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - run: git fetch --tags || true
      - name: Setup Windows C++ toolchain
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Build
        shell: bash
        run: |
          echo $(pwd)
          sbt clean example/nativeImage
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.local_path_1 }}
          name: ${{ matrix.uploaded_filename_1 }}
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.local_path_2 }}
          name: ${{ matrix.uploaded_filename_2 }}
      - name: Upload release 1
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path_1 }}
          asset_name: ${{ matrix.uploaded_filename_1 }}
          asset_content_type: application/zip
      - name: Upload release 2
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path_2 }}
          asset_name: ${{ matrix.uploaded_filename_2 }}
          asset_content_type: application/zip